name: layout_engine
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.3
  # Task 1: Added flutter_svg package to render vector graphics
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Task 3: Declared the assets folder
  # Including the trailing slash tells Flutter to include ALL files in this directory
  assets:
    - assets/icons/
